#!/usr/bin/env python3
"""Flyway 마이그레이션(db/migration/V*.sql)에서 docs/erd.dbml 을 만든다.

파일은 버전 차례로, 파일 안에서는 문장 차례로 적용한다. 뒤 마이그레이션이 걷은 외래 키 · 제약 · 인덱스는 ERD 에서도
빠지고, 새로 건 것은 더해진다. 읽는 DDL 은 아래와 같다.
  create table · drop table · create [unique] index
  alter table … add column · drop column · rename column … to … · alter column … set/drop not null
  alter table … add constraint(primary key · unique · foreign key · check) · drop constraint
insert · update · delete · select 는 건너뛴다. 이 밖의 DDL 을 만나면 ERD 를 내지 않고 그 문장을 stderr 에 적고 1로
끝낸다(모르는 문장을 조용히 건너뛰면 ERD 가 DB 와 어긋난다 — 예전 판이 drop constraint 를 건너뛰어 걷은 FK 가 남았다).

실행: python3 backend/scripts/ddl_to_dbml.py > docs/erd.dbml
다른 폴더를 읽으려면 첫 인자로 준다. 표준 출력은 콘솔 인코딩(cp949 등)과 상관없이 UTF-8 로 쓴다.
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[1] / "src/main/resources/db/migration"

# 문자열 리터럴 · 한 줄 주석 · 공백 · 세미콜론 · 그 밖의 글자. 문자열 안의 ; 와 -- 는 문장을 끊지 않는다.
TOKEN = re.compile(r"'(?:[^']|'')*'|--[^\n]*|\s+|;|[^'\s;-]+|-")
DML = re.compile(r"(insert|update|delete|select|with)\b", re.I)
COLUMN = re.compile(r"(\w+) (timestamp with time zone|\w+(?: ?\( ?\d+(?: ?, ?\d+)? ?\))?)(?: (.*))?", re.I)
# 컬럼 정의 뒤에 와도 되는 것. 이것을 다 지우고 남는 것이 있으면(인라인 제약 등) 모르는 정의로 본다.
COLUMN_EXTRA = re.compile(
    r"(?<!\w)(?:not null|null|generated by default as identity|default (?:'(?:[^']|'')*'|[\w.+-]+))(?!\w)", re.I)
TYPE_ALIAS = {"timestamp with time zone": "timestamptz", "integer": "int"}


class UnknownDdl(Exception):
    """이 스크립트가 반영할 줄 모르는 문장."""


@dataclass
class Index:
    columns: list[str]
    kind: str  # pk · unique · index


@dataclass
class Ref:
    table: str
    columns: list[str]
    target: str
    target_columns: list[str]


@dataclass
class Table:
    columns: list[list] = field(default_factory=list)  # [이름, 타입, [속성]]
    pk: str | None = None
    indexes: dict[str, Index] = field(default_factory=dict)
    checks: dict[str, str] = field(default_factory=dict)


@dataclass
class Schema:
    tables: dict[str, Table] = field(default_factory=dict)
    refs: dict[str, Ref] = field(default_factory=dict)

    def table(self, name: str) -> Table:
        if name not in self.tables:
            raise UnknownDdl(f"만든 적 없는 표: {name}")
        return self.tables[name]


def statements(text: str):
    """주석을 빼고 문자열 밖의 공백을 한 칸으로 줄인 문장들. 문자열 안은 그대로 둔다."""
    parts: list[str] = []
    for m in TOKEN.finditer(text):
        tok = m.group()
        if tok.startswith("--"):
            continue
        if tok == ";":
            yield "".join(parts).strip()
            parts = []
        else:
            parts.append(" " if tok.isspace() else tok)
    if "".join(parts).strip():
        yield "".join(parts).strip()


def split_top_level(body: str) -> list[str]:
    """괄호 밖 · 문자열 밖의 쉼표로 나눈다. 여러 줄에 걸친 제약도 한 항목이 된다."""
    items, buf, depth = [], [], 0
    for tok in re.findall(r"'(?:[^']|'')*'|[(),]|[^'(),]+", body):
        if tok == "," and depth == 0:
            items.append("".join(buf).strip())
            buf = []
            continue
        depth += {"(": 1, ")": -1}.get(tok, 0)
        buf.append(tok)
    items.append("".join(buf).strip())
    return [it for it in items if it]


def names(cols: str) -> list[str]:
    return [c.strip() for c in cols.split(",")]


def parse_column(text: str) -> list:
    m = COLUMN.fullmatch(text)
    if not m or m.group(1).lower() in ("constraint", "primary", "unique", "check", "foreign"):
        raise UnknownDdl(f"컬럼 정의를 읽지 못했다: {text}")
    rest = m.group(3) or ""
    if COLUMN_EXTRA.sub("", rest).strip():
        raise UnknownDdl(f"컬럼 정의에 모르는 부분이 있다: {text}")
    typ = re.sub(r"\s+", "", TYPE_ALIAS.get(m.group(2).lower(), m.group(2)))
    attrs = []
    if re.search(r"\bnot null\b", rest, re.I):
        attrs.append("not null")
    if re.search(r"generated by default as identity", rest, re.I):
        attrs.append("increment")
    return [m.group(1), typ, attrs]


def add_constraint(schema: Schema, tname: str, cname: str, body: str) -> None:
    t = schema.table(tname)
    if m := re.fullmatch(r"primary key ?\(([^()]*)\)", body, re.I):
        cols = names(m.group(1))
        if len(cols) == 1:
            t.pk = cols[0]
        else:
            t.indexes[cname] = Index(cols, "pk")
    elif m := re.fullmatch(r"unique ?\(([^()]*)\)", body, re.I):
        t.indexes[cname] = Index(names(m.group(1)), "unique")
    elif m := re.fullmatch(r"foreign key ?\(([^()]*)\) references (\w+) ?\(([^()]*)\)", body, re.I):
        schema.refs[cname] = Ref(tname, names(m.group(1)), m.group(2), names(m.group(3)))
    elif m := re.fullmatch(r"check (.+)", body, re.I | re.S):
        t.checks[cname] = m.group(1)
    else:
        raise UnknownDdl(f"제약을 읽지 못했다: {cname} {body}")


def drop_constraint(schema: Schema, tname: str, cname: str) -> None:
    t = schema.table(tname)
    found = [d for d in (schema.refs, t.indexes, t.checks) if cname in d]
    if not found:
        raise UnknownDdl(f"걷을 제약이 없다: {tname}.{cname}")
    for d in found:
        del d[cname]


def create_table(schema: Schema, tname: str, body: str) -> None:
    schema.tables[tname] = Table()
    for item in split_top_level(body):
        if m := re.fullmatch(r"constraint (\w+) (.+)", item, re.I | re.S):
            add_constraint(schema, tname, m.group(1), m.group(2))
        else:
            schema.tables[tname].columns.append(parse_column(item))


def column(t: Table, tname: str, cname: str) -> list:
    for col in t.columns:
        if col[0] == cname:
            return col
    raise UnknownDdl(f"없는 컬럼: {tname}.{cname}")


def rename_column(schema: Schema, tname: str, old: str, new: str) -> None:
    """PostgreSQL 처럼 컬럼을 가리키는 PK · 인덱스 · 외래 키 · check 도 새 이름을 따라간다."""
    t = schema.table(tname)
    column(t, tname, old)[0] = new
    rename = lambda cols: [new if c == old else c for c in cols]  # noqa: E731
    if t.pk == old:
        t.pk = new
    for idx in t.indexes.values():
        idx.columns = rename(idx.columns)
    for ref in schema.refs.values():
        if ref.table == tname:
            ref.columns = rename(ref.columns)
        if ref.target == tname:
            ref.target_columns = rename(ref.target_columns)
    for name, expr in t.checks.items():
        t.checks[name] = re.sub(rf"\b{re.escape(old)}\b", new, expr)


def drop_column(schema: Schema, tname: str, cname: str) -> None:
    """PostgreSQL 처럼 그 컬럼이 들어간 인덱스 · 제약도 같이 걷는다."""
    t = schema.table(tname)
    t.columns.remove(column(t, tname, cname))
    if t.pk == cname:
        t.pk = None
    t.indexes = {n: i for n, i in t.indexes.items() if cname not in i.columns}
    t.checks = {n: e for n, e in t.checks.items() if not re.search(rf"\b{re.escape(cname)}\b", e)}
    schema.refs = {
        n: r for n, r in schema.refs.items()
        if not (r.table == tname and cname in r.columns) and not (r.target == tname and cname in r.target_columns)
    }


def set_not_null(schema: Schema, tname: str, cname: str, action: str) -> None:
    attrs = column(schema.table(tname), tname, cname)[2]
    if action.lower() == "set" and "not null" not in attrs:
        attrs.insert(0, "not null")
    elif action.lower() == "drop" and "not null" in attrs:
        attrs.remove("not null")


def drop_table(schema: Schema, tname: str) -> None:
    """PostgreSQL 처럼 그 표가 건 외래 키도 같이 걷는다. 다른 표의 외래 키가 아직 가리키면 PostgreSQL 이 거절하므로(cascade
    없이) 여기서도 멈춘다 — 가리키는 표를 먼저 걷어야 한다."""
    schema.table(tname)
    blockers = [n for n, r in schema.refs.items() if r.target == tname and r.table != tname]
    if blockers:
        raise UnknownDdl(f"다른 표의 외래 키가 아직 가리킨다: {tname} ← {', '.join(blockers)}")
    del schema.tables[tname]
    schema.refs = {n: r for n, r in schema.refs.items() if r.table != tname}


def create_index(schema: Schema, unique: str | None, iname: str, tname: str, cols: str) -> None:
    schema.table(tname).indexes[iname] = Index(names(cols), "unique" if unique else "index")


HANDLERS = [
    (r"create table (\w+) ?\((.*)\)", create_table),
    (r"drop table (\w+)", drop_table),
    (r"create (unique )?index (\w+) on (\w+) ?\(([^()]*)\)", create_index),
    (r"alter table (\w+) add column (.+)",
     lambda s, t, c: s.table(t).columns.append(parse_column(c))),
    (r"alter table (\w+) drop column (\w+)", drop_column),
    (r"alter table (\w+) rename column (\w+) to (\w+)", rename_column),
    (r"alter table (\w+) alter column (\w+) (set|drop) not null", set_not_null),
    (r"alter table (\w+) add constraint (\w+) (.+)", add_constraint),
    (r"alter table (\w+) drop constraint (\w+)", drop_constraint),
]


def apply(schema: Schema, stmt: str) -> None:
    if not stmt or DML.match(stmt):
        return
    for pattern, handler in HANDLERS:
        if m := re.fullmatch(pattern, stmt, re.I | re.S):
            handler(schema, *m.groups())
            return
    raise UnknownDdl(f"모르는 문장: {stmt[:200]}")


def migrations(root: Path) -> list[Path]:
    def version(f: Path) -> tuple[int, ...]:
        return tuple(int(p) for p in re.split(r"[._]", re.match(r"V([\d._]+?)__", f.name).group(1)))

    return sorted(root.glob("V*__*.sql"), key=version)


def render_cols(table: str, cols: list[str]) -> str:
    return f"{table}.{cols[0]}" if len(cols) == 1 else f"{table}.({', '.join(cols)})"


def render_index(name: str, idx: Index) -> str:
    cols = f"({', '.join(idx.columns)})"
    if idx.kind == "pk":
        return f"{cols} [pk]"
    return f"{cols} [{'unique, ' if idx.kind == 'unique' else ''}name: '{name}']"


def render(schema: Schema) -> str:
    out = ["// 우리가족 체력키움 — ERD. backend/src/main/resources/db/migration 에서 생성한 것이라 손으로 고치지 않는다.",
           "// 재생성: python3 backend/scripts/ddl_to_dbml.py > docs/erd.dbml", ""]
    for name, t in schema.tables.items():
        out.append(f"Table {name} {{")
        for cname, typ, attrs in t.columns:
            a = (["pk"] if t.pk == cname else []) + attrs
            out.append(f"  {cname} {typ}" + (f" [{', '.join(a)}]" if a else ""))
        if t.indexes:
            out.append("  indexes {")
            out.extend(f"    {render_index(n, i)}" for n, i in t.indexes.items())
            out.append("  }")
        if t.checks:
            out.append("  Note: '''" + "\n".join(t.checks.values()) + "'''")
        out.append("}")
        out.append("")
    out.extend(f"Ref: {render_cols(r.table, r.columns)} > {render_cols(r.target, r.target_columns)}"
               for r in schema.refs.values())
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
    root = Path(argv[1]) if len(argv) > 1 else DEFAULT_ROOT
    files = migrations(root)
    if not files:
        print(f"마이그레이션 파일이 없다: {root}", file=sys.stderr)
        return 1
    schema, errors = Schema(), []
    for sql in files:
        for stmt in statements(sql.read_text(encoding="utf-8")):
            try:
                apply(schema, stmt)
            except UnknownDdl as e:
                errors.append(f"{sql.name}: {e}")
    if errors:
        print("ERD 를 만들지 않았다. 아래 문장을 이 스크립트에 가르쳐야 한다.", file=sys.stderr)
        print("\n".join(errors), file=sys.stderr)
        return 1
    sys.stdout.write(render(schema))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
