#!/usr/bin/env python3
"""Flyway 마이그레이션(db/migration/*.sql)에서 docs/erd.dbml 을 만든다.

이 저장소의 DDL 은 한 줄 = 한 컬럼/제약 형식으로 쓰므로 정규식으로 충분하다.
`alter table ... add column` 도 읽는다. 실행: python3 backend/scripts/ddl_to_dbml.py > docs/erd.dbml
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src/main/resources/db/migration"

tables: dict[str, dict] = {}
refs: list[str] = []
order: list[str] = []


def add_table(name: str) -> dict:
    if name not in tables:
        tables[name] = {"columns": [], "indexes": []}
        order.append(name)
    return tables[name]


def parse_column(line: str) -> tuple[str, str, list[str]] | None:
    m = re.match(
        r"^\s*([a-z_]+)\s+(timestamp with time zone|[a-z]+(?:\(\s*\d+(?:,\s*\d+)?\s*\))?)(?:\s+(.*))?,?\s*$",
        line,
    )
    if not m:
        return None
    name, typ, rest = m.group(1), m.group(2).strip(), (m.group(3) or "").rstrip(",").strip()
    if name in ("constraint", "primary", "unique", "check", "foreign"):
        return None
    attrs = []
    if "not null" in rest:
        attrs.append("not null")
    if "generated by default as identity" in rest:
        attrs.append("increment")
    typ = {"timestamp with time zone": "timestamptz", "integer": "int"}.get(typ, typ)
    typ = re.sub(r"\s+", "", typ)
    return name, typ, attrs


for sql in sorted(ROOT.glob("V*.sql"), key=lambda f: int(re.match(r"V(\d+)__", f.name).group(1))):
    text = sql.read_text(encoding="utf-8")
    for block in re.finditer(r"create table (\w+)\s*\((.*?)\n\);", text, re.S):
        tname, body = block.group(1), block.group(2)
        t = add_table(tname)
        for raw in body.splitlines():
            line = raw.strip().rstrip(",")
            if not line or line.startswith("--"):
                continue
            c = re.match(r"constraint (\w+) (.*)", line)
            if c:
                cname, cbody = c.groups()
                if cbody.startswith("primary key"):
                    cols = re.search(r"\((.*?)\)", cbody).group(1)
                    if "," in cols:
                        t["indexes"].append(f"({cols}) [pk]")
                    else:
                        t["pk"] = cols.strip()
                elif cbody.startswith("unique"):
                    cols = re.search(r"\((.*?)\)", cbody).group(1)
                    t["indexes"].append(f"({cols}) [unique, name: '{cname}']")
                elif cbody.startswith("foreign key"):
                    fk = re.match(r"foreign key \((\w+)\) references (\w+) \((\w+)\)", cbody)
                    refs.append(f"Ref: {tname}.{fk.group(1)} > {fk.group(2)}.{fk.group(3)}")
                elif cbody.startswith("check"):
                    t.setdefault("checks", []).append(cbody[len("check "):])
                continue
            col = parse_column(line)
            if col:
                t["columns"].append(col)
    for m in re.finditer(r"create index (\w+) on (\w+) \((.*?)\);", text):
        add_table(m.group(2))["indexes"].append(f"({m.group(3)}) [name: '{m.group(1)}']")
    for m in re.finditer(r"alter table (\w+) add column ([^;]+);", text):
        col = parse_column(m.group(2).strip())
        if col:
            add_table(m.group(1))["columns"].append(col)

out = ["// 우리가족 체력키움 — ERD. backend/src/main/resources/db/migration 에서 생성한 것이라 손으로 고치지 않는다.",
       "// 재생성: python3 backend/scripts/ddl_to_dbml.py > docs/erd.dbml", ""]
for name in order:
    t = tables[name]
    out.append(f"Table {name} {{")
    for cname, typ, attrs in t["columns"]:
        a = list(attrs)
        if t.get("pk") == cname:
            a.insert(0, "pk")
        out.append(f"  {cname} {typ}" + (f" [{', '.join(a)}]" if a else ""))
    if t["indexes"]:
        out.append("  indexes {")
        out.extend(f"    {i}" for i in t["indexes"])
        out.append("  }")
    if t.get("checks"):
        out.append("  Note: '''" + "\n".join(t["checks"]) + "'''")
    out.append("}")
    out.append("")
out.extend(refs)
sys.stdout.write("\n".join(out) + "\n")
