#!/usr/bin/env python3
"""family-fitness-ai 의 국민체력100 등급 기준표 `data/release/grade_thresholds.csv` → Flyway 마이그레이션.

기준표 한 줄은 (연령대 · 성별 · 나이 구간 · 등급 · 항목)의 공식 기준 하나다. AI 는 이 표로 인증 등급을 내고
(stats/tables.py certify), 서버도 같은 표 · 같은 규칙으로 한 사람에게 하나를 매긴다(fitness.domain.Certifier). 한 줄의 뜻은 AI 의
Threshold.passes() 와 같다.
  >=  값 ≥ cutoff          <=  값 ≤ cutoff          <  값 < cutoff          between  cutoff ≤ 값 ≤ cutoff_upper
나이 구간은 유아기만 개월(48~83), 나머지는 세다. age_unit 칸에 그대로 넣는다.
AI 표의 value2 는 between 에서만 뜻이 있어(그 밖은 0.0) cutoff_upper 는 between 일 때만 넣고 그 밖은 null 이다.
신체조성 줄(003 체지방률 · 018 BMI · 042 WHtR)도 그대로 넣는다. 3등급 판정에 쓴다(BMI · WHtR 은 키 · 몸무게 · 허리둘레로 셈한다).

낸 SQL 은 표를 통째로 바꾼다(delete 뒤 insert). 등급은 저장하지 않고 읽을 때 셈하므로 표를 바꾸면 지난 회차도 새 표를 따른다.
문장은 PostgreSQL 과 H2 양쪽에서 도는 것만 쓴다.

사용(backend 폴더에서):
  첫 적재(표 만들기 포함):
    python3 scripts/grade_thresholds_to_sql.py --create-table ../../family-fitness-ai \\
        > src/main/resources/db/migration/V154__fitness_grade_thresholds.sql
  다음 릴리스(표는 이미 있다):
    python3 scripts/grade_thresholds_to_sql.py ../../family-fitness-ai \\
        > src/main/resources/db/migration/V<다음 번호>__fitness_grade_thresholds_<AI 커밋>.sql
적용된 버전 마이그레이션은 고칠 수 없으니 새 판은 새 V 파일로 넣는다.
"""
import argparse
import csv
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

INPUT = "data/release/grade_thresholds.csv"
COLUMNS = ["age_group", "sex", "age_unit", "age_lo", "age_hi", "grade", "item_code", "op", "value", "value2"]
AGE_UNITS = {"유아기": "개월", "유소년": "세", "청소년": "세", "성인": "세", "어르신": "세"}
GRADES = ("1등급", "2등급", "3등급")
OPS = (">=", "<=", "<", "between")

CREATE_TABLE = """create table fitness_grade_thresholds (
    id           bigint generated by default as identity,
    age_group    varchar(10)   not null,
    sex          varchar(1)    not null,
    age_unit     varchar(4)    not null,
    age_from     smallint      not null,
    age_to       smallint      not null,
    grade        varchar(10)   not null,
    item_code    varchar(3)    not null,
    op           varchar(10)   not null,
    cutoff       numeric(8, 3) not null,
    cutoff_upper numeric(8, 3),
    constraint pk_fitness_grade_thresholds primary key (id),
    constraint uq_fitness_grade_threshold unique (age_group, sex, age_unit, age_from, age_to, grade, item_code),
    constraint ck_fitness_grade_thresholds_sex check (sex in ('M', 'F')),
    constraint ck_fitness_grade_thresholds_age_unit check (age_unit in ('세', '개월')),
    constraint ck_fitness_grade_thresholds_ages check (age_from <= age_to),
    constraint ck_fitness_grade_thresholds_grade check (grade in ('1등급', '2등급', '3등급')),
    constraint ck_fitness_grade_thresholds_op check (op in ('>=', '<=', '<', 'between')),
    constraint ck_fitness_grade_thresholds_upper check ((op = 'between' and cutoff_upper is not null)
        or (op <> 'between' and cutoff_upper is null))
);"""


def fail(message: str) -> None:
    sys.exit(f"grade_thresholds_to_sql: {message}")


def git(ai_root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(ai_root), *args], check=True, capture_output=True, text=True, encoding="utf-8"
    ).stdout.strip()


def number(text: str) -> str:
    """CSV 의 수를 그대로 싣는다. 소수 셋째 자리를 넘으면 numeric(8, 3) 이 반올림하므로 멈춘다."""
    value = float(text)
    if round(value, 3) != value:
        fail(f"소수 셋째 자리를 넘는 기준값: {text}")
    return repr(value)


def read_rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames != COLUMNS:
            fail(f"칸이 바뀌었다: {reader.fieldnames}")
        rows = list(reader)
    covered = defaultdict(list)
    for r in rows:
        if AGE_UNITS.get(r["age_group"]) != r["age_unit"]:
            fail(f"연령대와 나이 단위가 맞지 않는다: {r}")
        if r["sex"] not in ("M", "F") or r["grade"] not in GRADES or r["op"] not in OPS:
            fail(f"모르는 값: {r}")
        lo, hi = int(r["age_lo"]), int(r["age_hi"])
        if lo > hi:
            fail(f"나이 구간이 뒤집혔다: {r}")
        # 한 사람 · 한 등급 · 한 항목에 줄은 하나여야 한다 — 서버와 AI 가 같은 줄을 고르게 하려는 것이다.
        key = (r["age_group"], r["sex"], r["grade"], r["item_code"])
        for other_lo, other_hi in covered[key]:
            if lo <= other_hi and other_lo <= hi:
                fail(f"나이 구간이 겹친다: {key} {other_lo}~{other_hi} · {lo}~{hi}")
        covered[key].append((lo, hi))
    return rows


def insert(r: dict) -> str:
    upper = number(r["value2"]) if r["op"] == "between" else "null"
    return (
        "insert into fitness_grade_thresholds "
        "(age_group, sex, age_unit, age_from, age_to, grade, item_code, op, cutoff, cutoff_upper) values "
        f"('{r['age_group']}', '{r['sex']}', '{r['age_unit']}', {int(r['age_lo'])}, {int(r['age_hi'])}, "
        f"'{r['grade']}', '{r['item_code']}', '{r['op']}', {number(r['value'])}, {upper});"
    )


def main(ai_root: Path, create_table: bool) -> None:
    dirty = git(ai_root, "status", "--porcelain", "--", INPUT)
    if dirty:
        fail(f"AI 입력 파일에 커밋하지 않은 변경이 있다 — 커밋된 판으로만 만든다:\n{dirty}")
    head = git(ai_root, "rev-parse", "HEAD")
    release_commit, committed_at = git(ai_root, "log", "-1", "--format=%h %cI", "--", INPUT).split(" ", 1)
    rows = read_rows(ai_root / INPUT)
    groups = sorted({r["age_group"] for r in rows}, key=list(AGE_UNITS).index)

    out = sys.stdout
    out.reconfigure(encoding="utf-8", newline="\n")
    command = "scripts/grade_thresholds_to_sql.py" + (" --create-table" if create_table else "")
    print("-- fitness: 국민체력100 등급 기준표. 한 사람의 인증 등급을 이 표로 낸다(AI certify 와 같은 표).", file=out)
    print(f"-- {command} 가 생성한다. 손으로 고치지 말고, AI 릴리스가 바뀌면 새 V 파일로 다시 만든다.", file=out)
    print(f"-- 출처: family-fitness-ai HEAD {head} (입력 파일 마지막 변경 {release_commit}, {committed_at})", file=out)
    print(f"--   {INPUT} {len(rows)}행 · 연령대 {' · '.join(groups)}.", file=out)
    print("-- 한 줄의 뜻은 AI stats/tables.py Threshold.passes() 와 같다: >= · <= · < 는 cutoff 와 견주고,", file=out)
    print("--   between 은 cutoff ≤ 값 ≤ cutoff_upper. 유아기 나이 구간은 개월, 나머지는 세다.", file=out)
    print("-- 표를 통째로 바꾼다. 등급은 저장하지 않고 읽을 때 셈한다.", file=out)
    print("-- PostgreSQL 과 H2(MODE=PostgreSQL) 양쪽에서 그대로 실행되는 문법만 쓴다.", file=out)
    if create_table:
        print(CREATE_TABLE, file=out)
    print("delete from fitness_grade_thresholds;", file=out)
    for r in rows:
        print(insert(r), file=out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="family-fitness-ai 등급 기준표 → Flyway 마이그레이션 SQL")
    parser.add_argument("ai_root", type=Path, help="family-fitness-ai 저장소 경로")
    parser.add_argument(
        "--create-table",
        action="store_true",
        help="fitness_grade_thresholds 표 정의도 낸다. 첫 적재(V154)에만 쓴다.",
    )
    args = parser.parse_args()
    main(args.ai_root, args.create_table)
