#!/usr/bin/env python3
"""family-fitness-ai 의 또래 등급 비율 표 `data/release/grade_distribution.csv` → Flyway 마이그레이션(`fitness_grade_distribution`).

표 한 줄은 (연령대 · 성별 · 나이)의 한 등급(1등급 · 2등급 · 3등급 · 참가)에 든 사람 수와 비율이다. 국민체력100 공공데이터의
실제 인증 결과(원자료 CRTFC_FLAG_NM)를 AI 가 센 것이고, AI assess 의 peer_distribution 과 같다. 서버는 측정 결과의
인증 등급 옆에 같은 나이 · 성별 참가자의 등급별 비율로 싣는다(fitness.domain.GradeDistribution).
- 나이는 유아기만 개월(48~83), 나머지는 만 나이다. 표에 age_unit 칸이 없어 연령대로 정한다.
- 성인 · 청소년은 2025년 6월부터 1~6등급 체계로 바뀌어 네 등급 비율의 합이 1 에 못 미칠 수 있다. 그대로 넣는다.

낸 SQL 은 표를 통째로 바꾼다(delete 뒤 insert). 문장은 PostgreSQL 과 H2 양쪽에서 도는 것만 쓴다.

사용(backend 폴더에서, 파이썬은 AI 저장소의 .venv 를 써도 된다):
  첫 적재(표 만들기 포함):
    python scripts/grade_distribution_to_sql.py --create-table ../../family-fitness-ai \\
        > src/main/resources/db/migration/V159__fitness_grade_distribution.sql
  다음 릴리스(표는 이미 있다):
    python scripts/grade_distribution_to_sql.py ../../family-fitness-ai \\
        > src/main/resources/db/migration/V<다음 번호>__fitness_grade_distribution_<AI 커밋>.sql
적용된 버전 마이그레이션은 고칠 수 없으니 새 판은 새 V 파일로 넣는다.
"""
import argparse
import csv
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

INPUT = "data/release/grade_distribution.csv"
COLUMNS = ["age_group", "sex", "age", "grade", "n", "ratio"]
AGE_GROUPS = ("유아기", "유소년", "청소년", "성인", "어르신")
GRADES = ("1등급", "2등급", "3등급", "참가")

CREATE_TABLE = """create table fitness_grade_distribution (
    id        bigint generated by default as identity,
    age_group varchar(10)  not null,
    sex       varchar(1)   not null,
    age       smallint     not null,
    grade     varchar(10)  not null,
    n         integer      not null,
    ratio     numeric(5, 4) not null,
    constraint pk_fitness_grade_distribution primary key (id),
    constraint uq_fitness_grade_distribution unique (age_group, sex, age, grade),
    constraint ck_fitness_grade_distribution_sex check (sex in ('M', 'F')),
    constraint ck_fitness_grade_distribution_grade check (grade in ('1등급', '2등급', '3등급', '참가')),
    constraint ck_fitness_grade_distribution_ratio check (ratio between 0 and 1)
);"""


def fail(message: str) -> None:
    sys.exit(f"grade_distribution_to_sql: {message}")


def git(ai_root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(ai_root), *args], check=True, capture_output=True, text=True, encoding="utf-8"
    ).stdout.strip()


def ratio(text: str) -> str:
    """CSV 의 비율을 그대로 싣는다. 소수 넷째 자리를 넘으면 numeric(5, 4) 가 반올림하므로 멈춘다."""
    value = float(text)
    if round(value, 4) != value or not 0 <= value <= 1:
        fail(f"싣지 못하는 비율: {text}")
    return repr(value)


def read_rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames != COLUMNS:
            fail(f"칸이 바뀌었다: {reader.fieldnames}")
        rows = list(reader)
    grades = defaultdict(list)
    for r in rows:
        if r["age_group"] not in AGE_GROUPS or r["sex"] not in ("M", "F") or r["grade"] not in GRADES:
            fail(f"모르는 값: {r}")
        if int(r["n"]) < 0:
            fail(f"사람 수가 음수다: {r}")
        grades[(r["age_group"], r["sex"], int(r["age"]))].append(r["grade"])
    for key, seen in grades.items():
        if sorted(seen) != sorted(GRADES):
            fail(f"한 사람 칸에 등급 넷이 한 줄씩이 아니다: {key} {seen}")
    return rows


def insert(r: dict) -> str:
    return (
        "insert into fitness_grade_distribution (age_group, sex, age, grade, n, ratio) values "
        f"('{r['age_group']}', '{r['sex']}', {int(r['age'])}, '{r['grade']}', {int(r['n'])}, {ratio(r['ratio'])});"
    )


def main(ai_root: Path, create_table: bool) -> None:
    dirty = git(ai_root, "status", "--porcelain", "--", INPUT)
    if dirty:
        fail(f"AI 입력 파일에 커밋하지 않은 변경이 있다 — 커밋된 판으로만 만든다:\n{dirty}")
    head = git(ai_root, "rev-parse", "HEAD")
    release_commit, committed_at = git(ai_root, "log", "-1", "--format=%h %cI", "--", INPUT).split(" ", 1)
    rows = read_rows(ai_root / INPUT)
    groups = sorted({r["age_group"] for r in rows}, key=AGE_GROUPS.index)

    out = sys.stdout
    out.reconfigure(encoding="utf-8", newline="\n")
    command = "scripts/grade_distribution_to_sql.py" + (" --create-table" if create_table else "")
    print("-- fitness: 같은 나이 · 성별 참가자의 인증 등급별 비율(AI assess peer_distribution 과 같은 표).", file=out)
    print(f"-- {command} 가 생성한다. 손으로 고치지 말고, AI 릴리스가 바뀌면 새 V 파일로 다시 만든다.", file=out)
    print(f"-- 출처: family-fitness-ai HEAD {head} (입력 파일 마지막 변경 {release_commit}, {committed_at})", file=out)
    print(f"--   {INPUT} {len(rows)}행 · 연령대 {' · '.join(groups)}. 원자료는 국민체력100 인증 결과(CRTFC_FLAG_NM).", file=out)
    print("-- 나이는 유아기만 개월, 나머지는 만 나이다. 성인 · 청소년은 2025년 6월부터 1~6등급 체계라 네 비율의 합이", file=out)
    print("--   1 에 못 미칠 수 있다 — 그대로 싣는다.", file=out)
    print("-- 표를 통째로 바꾼다. PostgreSQL 과 H2(MODE=PostgreSQL) 양쪽에서 그대로 실행되는 문법만 쓴다.", file=out)
    if create_table:
        print(CREATE_TABLE, file=out)
    print("delete from fitness_grade_distribution;", file=out)
    for r in rows:
        print(insert(r), file=out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="family-fitness-ai 또래 등급 비율 표 → Flyway 마이그레이션 SQL")
    parser.add_argument("ai_root", type=Path, help="family-fitness-ai 저장소 경로")
    parser.add_argument(
        "--create-table",
        action="store_true",
        help="fitness_grade_distribution 표 정의도 낸다. 첫 적재(V159)에만 쓴다.",
    )
    args = parser.parse_args()
    main(args.ai_root, args.create_table)
