#!/usr/bin/env python3
"""family-fitness-ai 의 또래 분포 표 `data/release/value_quantiles.csv` → Flyway 마이그레이션(`fitness_value_quantiles`).

표 한 줄은 (연령대 · 성별 · 나이 · 항목)의 또래 분포 하나다. quantiles 는 0~100 백분위 101칸을 ; 로 이은 원래 글자
그대로 넣는다(숫자로 바꿨다 되돌리지 않는다 — AI 가 읽는 글자와 서버가 읽는 글자가 같아야 한다). 서버는 AI
stats/tables.py 의 peer() · percentile_of() 를 그대로 옮긴 fitness.domain.PeerTable 로 이 표에서 백분위를 낸다.
- 나이는 유아기만 개월(48~83), 나머지는 만 나이다. age_unit 칸에 그대로 넣는다.
- 표본이 30 미만(n < 30)인 줄도 넣는다. 백분위를 낼지는 서버가 n 을 보고 AI 처럼 정한다(MIN_SAMPLE).
- mean · sd 는 AI 의 0~100 점수(score_of)에만 쓰여 넣지 않는다. 서버는 점수를 내지 않는다.

낸 SQL 은 표를 통째로 바꾼다(delete 뒤 insert). 백분위는 측정을 등록할 때 굳으므로 표를 바꿔도 지난 회차는 그대로다.
문장은 PostgreSQL 과 H2 양쪽에서 도는 것만 쓴다.

사용(backend 폴더에서, 파이썬은 AI 저장소의 .venv 를 써도 된다):
  첫 적재(표 만들기 포함):
    python scripts/value_quantiles_to_sql.py --create-table ../../family-fitness-ai \\
        > src/main/resources/db/migration/V156__fitness_value_quantiles.sql
  다음 릴리스(표는 이미 있다):
    python scripts/value_quantiles_to_sql.py ../../family-fitness-ai \\
        > src/main/resources/db/migration/V<다음 번호>__fitness_value_quantiles_<AI 커밋>.sql
적용된 버전 마이그레이션은 고칠 수 없으니 새 판은 새 V 파일로 넣는다.
"""
import argparse
import csv
import subprocess
import sys
from pathlib import Path

INPUT = "data/release/value_quantiles.csv"
COLUMNS = ["age_group", "sex", "age_unit", "age", "item_code", "n", "mean", "sd", "quantiles"]
AGE_UNITS = {"유아기": "개월", "유소년": "세", "청소년": "세", "성인": "세", "어르신": "세"}
QUANTILES = 101
MAX_TEXT = 1000

CREATE_TABLE = f"""create table fitness_value_quantiles (
    id        bigint generated by default as identity,
    age_group varchar(10)   not null,
    sex       varchar(1)    not null,
    age_unit  varchar(4)    not null,
    age       smallint      not null,
    item_code varchar(3)    not null,
    n         integer       not null,
    quantiles varchar({MAX_TEXT}) not null,
    constraint pk_fitness_value_quantiles primary key (id),
    constraint uq_fitness_value_quantile unique (age_group, sex, age, item_code),
    constraint ck_fitness_value_quantiles_sex check (sex in ('M', 'F')),
    constraint ck_fitness_value_quantiles_age_unit check (age_unit in ('세', '개월')),
    constraint ck_fitness_value_quantiles_n check (n >= 0)
);"""


def fail(message: str) -> None:
    sys.exit(f"value_quantiles_to_sql: {message}")


def git(ai_root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(ai_root), *args], check=True, capture_output=True, text=True, encoding="utf-8"
    ).stdout.strip()


def read_rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames != COLUMNS:
            fail(f"칸이 바뀌었다: {reader.fieldnames}")
        rows = list(reader)
    seen = set()
    for r in rows:
        if AGE_UNITS.get(r["age_group"]) != r["age_unit"]:
            fail(f"연령대와 나이 단위가 맞지 않는다: {r['age_group']} {r['age_unit']}")
        if r["sex"] not in ("M", "F"):
            fail(f"모르는 성별: {r['sex']}")
        key = (r["age_group"], r["sex"], int(r["age"]), r["item_code"])
        if key in seen:
            fail(f"같은 칸이 두 줄이다: {key}")
        seen.add(key)
        text = r["quantiles"]
        values = [float(v) for v in text.split(";")]
        if len(values) != QUANTILES:
            fail(f"분위수가 {QUANTILES}칸이 아니다: {key}")
        # AI 는 np.searchsorted 로 자리를 찾는다. 정렬돼 있지 않으면 서버와 AI 가 다른 답을 낼 수 있다.
        if any(a > b for a, b in zip(values, values[1:])):
            fail(f"분위수가 오름차순이 아니다: {key}")
        if len(text) > MAX_TEXT or "'" in text:
            fail(f"quantiles 글자를 그대로 넣을 수 없다: {key}")
        if int(r["n"]) < 0:
            fail(f"표본 수가 음수다: {key}")
    return rows


def insert(r: dict) -> str:
    return (
        "insert into fitness_value_quantiles (age_group, sex, age_unit, age, item_code, n, quantiles) values "
        f"('{r['age_group']}', '{r['sex']}', '{r['age_unit']}', {int(r['age'])}, '{r['item_code']}', "
        f"{int(r['n'])}, '{r['quantiles']}');"
    )


def main(ai_root: Path, create_table: bool) -> None:
    dirty = git(ai_root, "status", "--porcelain", "--", INPUT)
    if dirty:
        fail(f"AI 입력 파일에 커밋하지 않은 변경이 있다 — 커밋된 판으로만 만든다:\n{dirty}")
    head = git(ai_root, "rev-parse", "HEAD")
    release_commit, committed_at = git(ai_root, "log", "-1", "--format=%h %cI", "--", INPUT).split(" ", 1)
    rows = read_rows(ai_root / INPUT)
    groups = sorted({r["age_group"] for r in rows}, key=list(AGE_UNITS).index)
    small = sum(1 for r in rows if int(r["n"]) < 30)

    out = sys.stdout
    out.reconfigure(encoding="utf-8", newline="\n")
    command = "scripts/value_quantiles_to_sql.py" + (" --create-table" if create_table else "")
    print("-- fitness: 또래 분포 표. 항목 백분위를 이 표로 낸다(AI stats/tables.py peer · percentile_of 와 같은 표).", file=out)
    print(f"-- {command} 가 생성한다. 손으로 고치지 말고, AI 릴리스가 바뀌면 새 V 파일로 다시 만든다.", file=out)
    print(f"-- 출처: family-fitness-ai HEAD {head} (입력 파일 마지막 변경 {release_commit}, {committed_at})", file=out)
    print(f"--   {INPUT} {len(rows)}행 · 연령대 {' · '.join(groups)} · 표본 30 미만 {small}행(백분위를 내지 않는다).", file=out)
    print("-- quantiles 는 0~100 백분위 101칸을 ; 로 이은 AI 원래 글자다. 유아기 나이는 개월, 나머지는 만 나이다.", file=out)
    print("-- 표를 통째로 바꾼다. 백분위는 측정을 등록할 때 굳으므로 지난 회차는 그대로다.", file=out)
    print("-- PostgreSQL 과 H2(MODE=PostgreSQL) 양쪽에서 그대로 실행되는 문법만 쓴다.", file=out)
    if create_table:
        print(CREATE_TABLE, file=out)
    print("delete from fitness_value_quantiles;", file=out)
    for r in rows:
        print(insert(r), file=out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="family-fitness-ai 또래 분포 표 → Flyway 마이그레이션 SQL")
    parser.add_argument("ai_root", type=Path, help="family-fitness-ai 저장소 경로")
    parser.add_argument(
        "--create-table",
        action="store_true",
        help="fitness_value_quantiles 표 정의도 낸다. 첫 적재(V156)에만 쓴다.",
    )
    args = parser.parse_args()
    main(args.ai_root, args.create_table)
