-- identity: 보호자 동의 이력. 동의를 주거나 거둘 때마다 한 줄씩 넣고, 고치거나 지우지 않는다.
-- 지금 동의 상태는 여전히 profiles 의 consent_* 칸이다. 재동의가 그 칸의 consent_revoked_at 을 걷어도 철회한 줄은 여기 남는다.
-- PostgreSQL 과 H2(MODE=PostgreSQL) 양쪽에서 그대로 실행되는 문법만 쓴다.
--
-- id 는 DB 가 매긴다(fitness_norms 와 같은 identity). 아래에서 지난 동의를 옮겨 넣을 때 두 DB 에 공통으로
-- uuid 를 만드는 함수가 없어서다.
-- kind          GRANTED(둘 다 동의) · REVOKED(하나라도 거둠)
-- actor_user_id 동의를 바꾼 계정. 옮겨 넣은 철회 줄은 누가 거뒀는지 남아 있지 않아 null 이다.
-- personal_data · health_data  보호자가 보낸 값. GRANTED 는 둘 다 true. 옮겨 넣은 철회 줄은 보낸 값이 남아 있지 않아 null 이다.
create table consent_events (
    id            bigint      generated by default as identity,
    profile_id    uuid        not null,
    actor_user_id uuid,
    kind          varchar(10) not null,
    personal_data boolean,
    health_data   boolean,
    occurred_at   timestamp with time zone not null,
    constraint pk_consent_events primary key (id),
    constraint fk_consent_events_profile foreign key (profile_id) references profiles (id),
    constraint fk_consent_events_actor foreign key (actor_user_id) references users (id),
    constraint ck_consent_events_kind check (kind in ('GRANTED', 'REVOKED')),
    constraint ck_consent_events_granted check (kind <> 'GRANTED' or (personal_data = true and health_data = true))
);
-- 한 사람의 동의 이력을 일어난 차례로.
create index ix_consent_events_profile on consent_events (profile_id, occurred_at);

-- 지난 동의를 옮겨 넣는다. profiles 에는 마지막 동의 한 번과 (거둔 채면) 마지막 철회 한 번만 남아 있어 그 둘만 옮긴다.
-- 재동의는 consent_revoked_at 을 걷었으므로 철회 칸이 있으면 그 철회는 마지막 동의보다 뒤다.
insert into consent_events (profile_id, actor_user_id, kind, personal_data, health_data, occurred_at)
select id, consent_by_user_id, 'GRANTED', true, true, consent_personal_at
from profiles
where consent_personal_at is not null and consent_health_at is not null;

insert into consent_events (profile_id, actor_user_id, kind, personal_data, health_data, occurred_at)
select id, null, 'REVOKED', null, null, consent_revoked_at
from profiles
where consent_revoked_at is not null;

-- 프로필 행의 낙관적 잠금 버전(JPA @Version). 저장소는 가족을 저장할 때 프로필 행의 모든 칸을 다시 쓴다.
-- 버전을 보지 않으면 먼저 읽고 늦게 저장한 요청이, 그 사이 다른 요청이 커밋한 이름 · 동의 · 붙은 계정(user_id)을 옛 값으로 덮는다.
-- 이제 UPDATE 가 읽을 때의 버전을 조건으로 걸고 1 을 더한다. 0행이면 저장소가 409 CONFLICT 로 돌린다.
-- 초대 코드 사용의 조건부 UPDATE 도 버전을 올린다. 기존 행과 날것 SQL 로 넣는 행은 0 에서 시작한다.
alter table profiles add column version bigint default 0 not null;
